### ISSUE TITLE
Error on running logger

### ISSUE THREAD

**Issue by netrunn3r** [maksbrz184/ETWCustomLogger#2]
After creating service (running as local system), in Logs.txt I have this message:

> 2020-03-03 17:55:55.6800 Initialising the ETWEngine Class.
> 2020-03-03 17:55:55.7070 Failed to properly create LoggingController System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
>    at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.LoadKernelTraceControl()
>    at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.StartKernelSession(UInt64& TraceHandle, Void* propertyBuff, Int32 propertyBuffLength, STACK_TRACING_EVENT_ID* stackTracingEventIds, Int32 cStackTracingEventIds)
>    at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
>    at ETWLogger.Library.LoggingController..ctor() in E:\ETWLogger\Library\LoggingController.cs:line 55
> 2020-03-03 17:55:55.7150 Creating ETWLoggerService
> 2020-03-03 17:55:55.7150 Starting service
> 2020-03-03 17:55:55.7150 Starting processing events
> 2020-03-03 17:55:55.7150 Filed to start processing events. System.NullReferenceException: Object reference not set to an instance of an object.
>    at ETWLogger.Library.LoggingController.Start() in E:\ETWLogger\Library\LoggingController.cs:line 107

In Windows feature I installed .Net Framework 3.5 (someone on Internet say it could help). I Have Windows 10 1909, just clone this repo and build in Visual Studio (Community 2019 Version 16.4.2)

**Comment by CyberzSentry** [comment]
A temporary fix to this problem is compiling of the solution in "Release" instead of the "Debug" mode. 

![obraz](https://user-images.githubusercontent.com/23097477/75814171-90d8f480-5d91-11ea-845f-9f5815cbeb27.png)


This fixed the problem in my tests. Will continue to search for the root cause and mitigate the problem completely. 

Edit:
Please let me know if this helped.

**Comment by CyberzSentry** [comment]
Update.
In order to install the newly compiled "Release" mode service, a uninstallation of the previous version with the use of "Install.bat" script is required as well as restart of the operating system.

**Comment by netrunn3r** [comment]
In Release it works, thanks!
